import { PRICE_OPTIONS } from "src/constants";

export const getFields = (productTypeData = []) => [
  { name: 'title', label: 'Title', fullWidth: true, required: true },
  {
    name: 'productTypeIds',
    label: 'Product Types',
    type: 'select',
    multiple: true,
    options: productTypeData?.map((pt) => ({ label: pt.name, value: pt.id })),
  },
  {
    name: 'designType',
    label: 'Default Design Type',
    type: 'select',
    options: [
      { label: 'CLONE', value: 'CLONE' },
      { label: 'RE_DESIGN', value: 'RE_DESIGN' },
      { label: 'NEW', value: 'NEW' },
    ],
  },
];

export const getFieldsIdeas = (productTypeData = [], templatesData = []) => [
  { name: 'title', label: 'Title', width: '75%', location: 'left', required: true },
  { name: 'description', label: 'Description', width: '75%', location: 'left' },
  {
    name: 'images',
    label: 'Images',
    type: 'file',
    width: '75%',
    location: 'left',
    required: true,
    multiple: true,
  },
  {
    name: 'designType',
    label: 'Default Design Type',
    type: 'select',
    width: '25%',
    location: 'right',
    options: [
      { label: 'CLONE', value: 'CLONE' },
      { label: 'RE_DESIGN', value: 'RE_DESIGN' },
      { label: 'NEW', value: 'NEW' },
    ],
  },
  {
    name: 'productTypeId',
    label: 'Product Type',
    type: 'select',
    width: '25%',
    location: 'right',
    multiple: false,
    options: productTypeData?.map((pt) => ({ label: pt.name, value: pt.id })),
  },
  {
    name: 'quantity',
    label: 'Quantity',
    width: '25%',
    location: 'right',
    require: false,
    default: 1,
    type: 'number',
    inputMode: 'numeric',
    pattern: '[0-9]*',
  },
  {
    name: 'number',
    label: 'Number',
    width: '25%',
    location: 'right',
    require: false,
    default: 1,
    type: 'number',
    inputMode: 'numeric',
    pattern: '[0-9]*',
  },
  {
    name: 'completed_at',
    label: 'Deadline',
    type: 'date',
    width: '25%',
    location: 'right',
  },
  {
    name: 'price',
    label: 'Price',
    type: 'select',
    width: '25%',
    location: 'right',
    required: true,
    options: PRICE_OPTIONS,
  },
  {
    name: 'templates',
    label: 'Templates',
    type: 'select',
    width: '25%',
    location: 'right',
    multiple: true,
    options: templatesData.map((tp) => ({ label: tp.title, value: tp.id })),
  },
];
